-- --------------------------------------------------------
-- 主机:                           127.0.0.1
-- 服务器版本:                        10.3.16-MariaDB - mariadb.org binary distribution
-- 服务器操作系统:                      Win64
-- HeidiSQL 版本:                  9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 导出  表 toolsweb.processes 结构
DROP TABLE IF EXISTS `processes`;
CREATE TABLE IF NOT EXISTS `processes` (
  `ProcessOID` int(11) NOT NULL AUTO_INCREMENT,
  `ProcessOIDParent` int(11) NOT NULL DEFAULT 0,
  `ProcessAID` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT 'AID',
  `Name` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT 'Name',
  `Category` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `Description` varchar(256) COLLATE utf8_bin DEFAULT NULL,
  `ExecType` int(11) NOT NULL DEFAULT 0,
  `ExecMode` int(11) NOT NULL DEFAULT 0,
  `ExecName` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `Route` varchar(128) COLLATE utf8_bin DEFAULT NULL,
  `ArgumentList` varchar(512) COLLATE utf8_bin DEFAULT NULL,
  `LevelNumber` int(11) NOT NULL DEFAULT 0,
  `SortNumber` int(11) NOT NULL DEFAULT 0,
  `ImageAID` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `ColorOdd` int(11) DEFAULT NULL,
  `ColorEven` int(11) DEFAULT NULL,
  `Hidden` int(11) DEFAULT NULL,
  PRIMARY KEY (`ProcessOID`),
  UNIQUE KEY `UNIQUE` (`ProcessAID`)
) ENGINE=InnoDB AUTO_INCREMENT=305 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 正在导出表  toolsweb.processes 的数据：~123 rows (大约)
/*!40000 ALTER TABLE `processes` DISABLE KEYS */;
REPLACE INTO `processes` (`ProcessOID`, `ProcessOIDParent`, `ProcessAID`, `Name`, `Category`, `Description`, `ExecType`, `ExecMode`, `ExecName`, `Route`, `ArgumentList`, `LevelNumber`, `SortNumber`, `ImageAID`, `ColorOdd`, `ColorEven`, `Hidden`) VALUES
	(97, 106, 'System Log', '系统日志', 'Root', '', 4, 0, '/app/system/log/showLoginLogs', '0', NULL, 2, 500, '', NULL, NULL, 0),
	(104, 106, 'Users', '系统用户', 'Root', '', 0, 0, '/app/system/authority2/user/showUsers', '0', NULL, 1, 100, '', NULL, NULL, 0),
	(106, 93, 'Authority', 'FOIL系统', 'Root', '', 4, 0, '', '0', NULL, 2, 400, '/images/menu_icon/system.png', NULL, NULL, 0),
	(146, 106, 'Processes', '系统功能', NULL, '', 0, 0, '/app/system/authority2/process/showProcesses', '0', NULL, 0, 0, '', NULL, NULL, 0),
	(163, 106, 'RoleAthority', '系统授权', NULL, '', 0, 0, '/app/system/authority2/roleAuthority/showRoleAuthority', '0', NULL, 0, 3, '', NULL, NULL, 0),
	(164, 106, 'Roles', '系统角色', NULL, '', 0, 0, '/app/system/authority2/role/showRoles', '0', NULL, 0, 2, '', NULL, NULL, 0),
	(169, 106, 'Orgs', '系统组织', NULL, '', 0, 0, '/app/system/authority2/org/showOrgs', '0', NULL, 0, 1, '', NULL, NULL, 0),
	(172, -1, 'Demo', '功能示例', NULL, '', 0, 0, '', NULL, NULL, 0, 80, '/images/menu_icon/olive.png', NULL, NULL, 0),
	(173, 172, 'bearSub', 'MES 数据接口', NULL, '', 0, 0, '/app/bear/BearSub', NULL, NULL, 0, 81, '', NULL, NULL, 0),
	(174, 172, 'uploadPic', '文件上传', NULL, '', 0, 0, '/app/bear/uploadPic', NULL, NULL, 0, 82, '', NULL, NULL, 0),
	(176, 172, 'bearTest', '子测试页', NULL, '', 0, 0, '/app/bear/BearTest', NULL, NULL, 0, 84, '', NULL, NULL, 0),
	(177, -1, 'MSTools', '停机密码工具', NULL, '', 0, 0, '', NULL, NULL, 0, 3, '/images/menu_icon/olive.png', NULL, NULL, 0),
	(178, 184, 'MSAkey', '单密钥', NULL, '', 0, 0, '/app/MSAgent/MSAkey', NULL, NULL, 0, 21, '', NULL, NULL, 0),
	(179, 184, 'MSAKeyG', '分期密钥', NULL, '', 0, 0, '/app/MSAgent/MSAkeyG', NULL, NULL, 0, 22, '', NULL, NULL, 0),
	(180, 184, 'MSAdmin', '密钥管理', NULL, '', 0, 0, '/app/MSAgent/MSAdmin', NULL, NULL, 0, 23, '', NULL, NULL, 0),
	(181, -1, 'HMIPrint', '面板解析工具', NULL, '', 0, 0, '', NULL, NULL, 0, 10, '/images/menu_icon/olive.png', NULL, NULL, 0),
	(182, 229, 'TM55维护', 'TM55模具维护', NULL, '', 0, 0, '/app/HMIPrint/Mold/MoldTM55DB', NULL, NULL, 0, 4, '', NULL, NULL, 0),
	(183, 228, 'moni解析', '监测信息', NULL, '', 0, 0, '/app/HMIPrint/Moni/moniParse', NULL, NULL, 0, 12, '', NULL, NULL, 0),
	(184, 177, 'MSAgent', '密钥生成', NULL, '', 0, 0, '', NULL, NULL, 0, 20, '', NULL, NULL, 0),
	(187, 184, 'MSDecrypt', '密钥解密', NULL, '', 0, 0, '/app/MSAgent/MSDecrypt', NULL, NULL, 0, 24, '', NULL, NULL, 0),
	(188, 229, 'mold解析', '模具信息', NULL, '', 0, 0, '/app/HMIPrint/Mold/MoldParse', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(189, 181, 'error', '警报信息', NULL, '', 0, 0, '/app/HMIPrint/error', NULL, NULL, 0, 15, '', NULL, NULL, 0),
	(190, 228, 'moni维护', '监测维护', NULL, '', 0, 0, '/app/HMIPrint/Moni/monidb', NULL, NULL, 0, 13, '', NULL, NULL, 0),
	(191, 177, 'MSSoftware', '单机软件', NULL, '', 0, 0, '', NULL, NULL, 0, 30, '', NULL, NULL, 0),
	(192, 191, 'MSMac', '软件注册码', NULL, '', 0, 0, '/app/MSSoftware/MSMac', NULL, NULL, 0, 31, '', NULL, NULL, 0),
	(193, 191, 'MSFac', '厂商授权码', NULL, '', 0, 0, '/app/MSSoftware/MSFacMK', NULL, NULL, 0, 32, '', NULL, NULL, 0),
	(194, -1, 'PPMTools', 'PPM工具', NULL, '', 0, 0, '', NULL, NULL, 0, 2, '/images/menu_icon/olive.png', NULL, NULL, 0),
	(195, 194, 'PPMBasicInfo', '基础信息', NULL, '', 0, 0, '', NULL, NULL, 0, 51, '', NULL, NULL, 0),
	(196, 194, 'PPMWorkFlow', '工作流程', NULL, '', 0, 0, '', NULL, NULL, 0, 52, '', NULL, NULL, 0),
	(197, 194, 'PPMInfoManage', '信息管理', NULL, '', 0, 0, '', NULL, NULL, 0, 54, '', NULL, NULL, 0),
	(198, 195, 'customers', '客户', NULL, '', 0, 0, '/app/PM/customers', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(200, 195, 'staffs', '人员', NULL, '', 0, 0, '/app/PM/staffs', NULL, NULL, 0, 3, '', NULL, NULL, 0),
	(201, 195, 'MHESystems', '系统', NULL, '', 0, 0, '/app/PM/MHESystems', NULL, NULL, 0, 6, '', NULL, NULL, 0),
	(202, 195, 'machines', '机种', NULL, '', 0, 0, '/app/PM/machines', NULL, NULL, 0, 5, '', NULL, NULL, 0),
	(203, 196, 'workFlow', '流程图', NULL, '', 0, 0, '/app/PM/workFlow', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(204, 196, 'billsPLD', '计划单', NULL, '', 0, 0, '/app/PM/billsPLD', NULL, NULL, 0, 4, '', NULL, NULL, 0),
	(205, 196, 'billsIPQC', 'IPQC单', NULL, '', 0, 0, '/app/PM/billsIPQC', NULL, NULL, 0, 7, '', NULL, NULL, 0),
	(206, 196, 'billsFQC', 'FQC单', NULL, '', 0, 0, '/app/PM/billsFQC', NULL, NULL, 0, 8, '', NULL, NULL, 0),
	(207, 196, 'billsFBK', '反馈单', NULL, '', 0, 0, '/app/PM/billsFBK', NULL, NULL, 0, 10, '', NULL, NULL, 0),
	(210, 197, 'oldbills', '老系统单据', NULL, '', 0, 0, '/app/PM/oldbills', NULL, NULL, 0, 9, '', NULL, NULL, 0),
	(211, -1, 'OATools', 'OA管理工具', NULL, '', 0, 0, '', NULL, NULL, 0, 60, '/images/menu_icon/olive.png', NULL, NULL, 0),
	(212, 211, 'OABasicInfo', '基础信息', NULL, '', 0, 0, '', NULL, NULL, 0, 61, '', NULL, NULL, 0),
	(214, 212, 'OA_Staffs', '人员信息查询', NULL, '', 0, 0, '/app/OA/OA_Staffs', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(215, 194, 'PPMFun', '功能模块', NULL, '', 0, 0, '', NULL, NULL, 0, 55, '', NULL, NULL, 0),
	(216, 215, 'DB', '数据库模块', NULL, '', 0, 0, '/app/PM/0DB', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(217, 215, 'ORDER', '表单模块', NULL, '', 0, 0, '/app/PM/0ORDER', NULL, NULL, 0, 2, '', NULL, NULL, 0),
	(218, 212, 'OA_StaffsAdmin', '人员信息管理', NULL, '', 0, 0, '/app/OA/OA_StaffsAdmin', NULL, NULL, 0, 2, '', NULL, NULL, 0),
	(219, 215, 'ORDERS', '表单跟踪模块', NULL, '', 0, 0, '/app/PM/0ORDERS', NULL, NULL, 0, 3, '', NULL, NULL, 0),
	(220, 215, 'ORDERSADMIN', '表单管理模块', NULL, '', 0, 0, '/app/PM/0ORDERSADMIN', NULL, NULL, 0, 4, '', NULL, NULL, 0),
	(221, 215, 'DingTalk', '钉钉机器人模块', NULL, '', 0, 0, '/app/PM/0DingTalk', NULL, NULL, 0, 5, '', NULL, NULL, 0),
	(222, 215, 'DBBind', '数据绑定模块', NULL, '', 0, 0, '/app/PM/0DBBind', NULL, NULL, 0, 6, '', NULL, NULL, 0),
	(223, 196, 'billsRQD', '需求单', NULL, '', 0, 0, '/app/PM/prebillsRQD', NULL, NULL, 0, 3, '', NULL, NULL, 0),
	(224, 196, 'billsTrack', '进度跟踪', NULL, '', 0, 0, '/app/PM/billsTrack', NULL, NULL, 0, 2, '', NULL, NULL, 0),
	(225, 196, 'billsBPT', '方案单', NULL, '', 0, 0, '/app/PM/billsBPT', NULL, NULL, 0, 5, '', NULL, NULL, 0),
	(226, 196, 'billsTask', '任务单', NULL, '', 0, 0, '/app/PM/billsTask', NULL, NULL, 0, 6, '', NULL, NULL, 0),
	(227, 196, 'billsPBH', '发布单', NULL, '', 0, 0, '/app/PM/billsPBH', NULL, NULL, 0, 9, '', NULL, NULL, 0),
	(228, 181, 'moni 模块', '监测模块', NULL, '', 0, 0, '', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(229, 181, 'mold 模块', '模具模块', NULL, '', 0, 0, '', NULL, NULL, 0, 2, '', NULL, NULL, 0),
	(230, 229, 'TM54维护', 'TM54模具维护', NULL, '', 0, 0, '/app/HMIPrint/Mold/MoldTM54DB', NULL, NULL, 0, 3, '', NULL, NULL, 0),
	(231, 195, 'testContents', '测试内容', NULL, '', 0, 0, '/app/PM/testContents', NULL, NULL, 0, 8, '', NULL, NULL, 0),
	(232, 194, 'PPMTFlow', '内核流程', NULL, '', 0, 0, '', NULL, NULL, 0, 53, '', NULL, NULL, 0),
	(233, 232, 'T-billsPLD', 'T计划单', NULL, '', 0, 0, '/app/PM/T-billsPLD', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(234, 232, 'T-billsBPT', 'T方案单', NULL, '', 0, 0, '/app/PM/T-billsBPT', NULL, NULL, 0, 2, '', NULL, NULL, 0),
	(235, 232, 'T-billsTask', 'T任务单', NULL, '', 0, 0, '/app/PM/T-billsTask', NULL, NULL, 0, 3, '', NULL, NULL, 0),
	(236, 196, 'workCenter', '个人中心', NULL, '', 0, 0, '/app/PM/workCenter', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(237, 232, 'T-billsIPQC', 'T-IPQC单', NULL, '', 0, 0, '/app/PM/T-billsIPQC', NULL, NULL, 0, 4, '', NULL, NULL, 0),
	(238, 232, 'T-billsTrack', 'T-进度跟踪', NULL, '', 0, 0, '/app/PM/T-billsTrack', NULL, NULL, 0, 0, '', NULL, NULL, 0),
	(239, 232, 'T-billsFQC', 'T-FQC单', NULL, '', 0, 0, '/app/PM/T-billsFQC', NULL, NULL, 0, 5, '', NULL, NULL, 0),
	(240, 232, 'T-billsPBH', 'T发布单', NULL, '', 0, 0, '/app/PM/T-billsPBH', NULL, NULL, 0, 6, '', NULL, NULL, 0),
	(241, 195, 'roles', '角色', NULL, '', 0, 0, '/app/PM/roles', NULL, NULL, 0, 7, '', NULL, NULL, 0),
	(242, 195, 'dataBinds', '数据关系', NULL, '', 0, 0, '/app/PM/dataBinds', NULL, NULL, 0, 9, '', NULL, NULL, 0),
	(243, -1, 'AutoTest', '自动测试工具', NULL, '', 0, 0, '', NULL, NULL, 0, 5, '/images/menu_icon/olive.png', NULL, NULL, 0),
	(244, 243, 'Major', '执行', NULL, '', 0, 0, '/app/AutoTest/autotest-Major', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(245, 197, 'billsDBCenter', '计划单', NULL, '', 0, 0, '/app/PM/billsDBCenter?trackType=all', NULL, NULL, 0, 1, '', NULL, NULL, 0),
	(246, 197, 'T-billsDBCenter', 'T计划单', NULL, NULL, 0, 0, '/app/PM/T-billsDBCenter?trackType=all', NULL, NULL, 0, 3, NULL, NULL, NULL, 0),
	(247, 197, 'tasksDBCenter', '任务单', NULL, NULL, 0, 0, '/app/PM/tasksDBCenter?trackType=all', NULL, NULL, 0, 2, NULL, NULL, NULL, 0),
	(248, 197, 'T-tasksDBCenter', 'T任务单', NULL, NULL, 0, 0, '/app/PM/T-tasksDBCenter?trackType=all', NULL, NULL, 0, 4, NULL, NULL, NULL, 0),
	(249, -1, 'RepairTools', '内修系统工具', NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 1, '/images/menu_icon/olive.png', NULL, NULL, 0),
	(250, 249, 'BasicDB', '基础数据', NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, 0),
	(252, 250, 'rpCustomers', '客户', NULL, NULL, 0, 0, '/app/RP/customers', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(253, 250, 'rpStaffs', '人员', NULL, NULL, 0, 0, '/app/RP/staffs', NULL, NULL, 0, 2, NULL, NULL, NULL, 0),
	(254, 250, 'rpProducts', '产品', NULL, NULL, 0, 0, '/app/RP/products', NULL, NULL, 0, 3, NULL, NULL, NULL, 0),
	(255, 250, 'partsFee', '零件费', NULL, NULL, 0, 0, '/app/RP/partsFee', NULL, NULL, 0, 4, NULL, NULL, NULL, 0),
	(256, 250, 'rpFaultClasses', '故障分类', NULL, NULL, 0, 0, '/app/RP/faultClasses', NULL, NULL, 0, 5, NULL, NULL, NULL, 0),
	(257, 249, 'RepairFlow', '维修流程', NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(258, 257, 'workFlowPic', '工作流程图', NULL, NULL, 0, 0, '/app/RP/workFlow', NULL, NULL, 0, 0, NULL, NULL, NULL, 0),
	(259, 257, 'rpRequestBill', '维修申请单', NULL, NULL, 0, 0, '/app/RP/requestBills', NULL, NULL, 0, 2, NULL, NULL, NULL, 0),
	(260, 257, 'rpRecordBill', '维修记录单', NULL, NULL, 0, 0, '/app/RP/recordBills', NULL, NULL, 0, 3, NULL, NULL, NULL, 0),
	(261, 257, 'rpResponseBill', '维修出货单', NULL, NULL, 0, 0, '/app/RP/responseBills', NULL, NULL, 0, 4, NULL, NULL, NULL, 0),
	(262, 257, 'rpShowPanel', '显示面板', NULL, NULL, 0, 0, '/app/RP/showPanels', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(263, 249, 'test', '测试', NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 99, NULL, NULL, NULL, 0),
	(264, 263, 'test1', '模块测试', NULL, NULL, 0, 0, '/app/RP/test1', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(265, 197, 'reportBugRate', '报表下载', NULL, NULL, 0, 0, '/app/PM/bugRate', NULL, NULL, 0, 5, NULL, NULL, NULL, 0),
	(266, 263, 'test2', '二维码生成', NULL, NULL, 0, 0, '/app/RP/test-qrcodeCreate', NULL, NULL, 0, 2, NULL, NULL, NULL, 0),
	(267, 263, 'test3', '二维码扫描', NULL, NULL, 0, 0, '/app/RP/test-qrcodeScan', NULL, NULL, 0, 3, NULL, NULL, NULL, 0),
	(268, 263, 'test4', '短信', NULL, NULL, 0, 0, '/app/RP/test4', NULL, NULL, 0, 4, NULL, NULL, NULL, 0),
	(269, 250, 'rpTestPrices', '检测项目', NULL, NULL, 0, 0, '/app/RP/testItems', NULL, NULL, 0, 6, NULL, NULL, NULL, 0),
	(270, 249, 'billsCenter', '单据中心', NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 2, NULL, NULL, NULL, 0),
	(271, 270, 'billsDB', '历史单据', NULL, NULL, 0, 0, '/app/RP/billsDB', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(272, 270, 'oldBills', '老系统单据', NULL, NULL, 0, 0, '/app/RP/oldBills', NULL, NULL, 0, 2, NULL, NULL, NULL, 0),
	(273, 172, 'ticketPrint', '打印小票', NULL, NULL, 0, 0, '/app/bear/TicketPrint', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(274, 263, 'FastDelivery', '快递', NULL, NULL, 0, 0, '/app/RP/funsTest/FastDelivery', NULL, NULL, 0, 5, NULL, NULL, NULL, 0),
	(275, 263, 'test5', '富文本框', NULL, NULL, 0, 0, '/app/RP/test5', NULL, NULL, 0, 6, NULL, NULL, NULL, 0),
	(276, 250, 'rpSelectorOptions', '选项清单', NULL, NULL, 0, 0, '/app/RP/selectorOptions', NULL, NULL, 0, 8, NULL, NULL, NULL, 0),
	(277, -1, 'TMCode', '物料审批工具', NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 6, '	 /images/menu_icon/olive.png', NULL, NULL, 0),
	(278, 277, 'NewProduct', '新品编码提交', NULL, NULL, 0, 0, '/app/TMCode/newProduct', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(279, 277, 'AgreeProduct', '新品编码审批', NULL, NULL, 0, 0, '/app/TMCode/agreeProduct', NULL, NULL, 0, 2, NULL, NULL, NULL, 0),
	(280, 277, 'AbsoleteProduct', '产品编码报废', NULL, NULL, 0, 0, '/app/TMCode/absoleteProduct', NULL, NULL, 0, 3, NULL, NULL, NULL, 0),
	(281, 277, 'FindProduct', '正式编码查找', NULL, NULL, 0, 0, '/app/TMCode/findProduct', NULL, NULL, 0, 4, NULL, NULL, NULL, 0),
	(282, 263, 'print', '打印', NULL, NULL, 0, 0, '/app/RP/funsTest/TicketPrint', NULL, NULL, 0, 7, NULL, NULL, NULL, 0),
	(283, 263, 'test6', '图表', NULL, NULL, 0, 0, '/app/RP/test6', NULL, NULL, 0, 8, NULL, NULL, NULL, 0),
	(284, 263, 'test7', '上传', NULL, NULL, 0, 0, '/app/RP/test7', NULL, NULL, 0, 9, NULL, NULL, NULL, 0),
	(285, 249, 'DataApi', '数据接口', NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 4, NULL, NULL, NULL, 0),
	(286, 285, 'store', '库存接口', NULL, NULL, 0, 0, '/app/RP/store', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(287, 197, 'reportBugRate_t', 'T报表下载', NULL, NULL, 0, 0, '/app/PM/bugRate_t', NULL, NULL, 0, 6, NULL, NULL, NULL, 0),
	(288, 172, 'bearSub2', '测试', NULL, NULL, 0, 0, '/app/bear/BearSub2', NULL, NULL, 0, 85, NULL, NULL, NULL, 0),
	(289, 263, 'test-jsBarcode', '条形码生成', NULL, NULL, 0, 0, '/app/RP/test-JsBarcodeCreate', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(290, 263, 'closeTab', 'tab页', NULL, NULL, 0, 0, '/app/RP/closeTab', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(291, 257, 'tabCustomer', '客户', NULL, NULL, 0, 0, '/app/RP/tabCustomers', NULL, NULL, 0, 100, NULL, NULL, NULL, 1),
	(292, 257, 'tabStaff', '人员', NULL, NULL, 0, 0, '/app/RP/tabStaffs', NULL, NULL, 0, 100, NULL, NULL, NULL, 1),
	(293, 257, 'tabRequestBill', '申请单', NULL, NULL, 0, 0, '/app/RP/tabRequestBills', NULL, NULL, 0, 100, NULL, NULL, NULL, 1),
	(294, 257, 'tabRecordBill', '记录单', NULL, NULL, 0, 0, '/app/RP/tabRecordBills', NULL, NULL, 0, 100, NULL, NULL, NULL, 1),
	(295, 257, 'closeTabs', '操作中心', NULL, NULL, 0, 0, '/app/RP/closeTabs', NULL, NULL, 0, 0, NULL, NULL, NULL, 0),
	(296, 250, 'rpWarehouses', '仓库', NULL, NULL, 0, 0, '/app/RP/warehousesList', NULL, NULL, 0, 7, NULL, NULL, NULL, 0),
	(297, 249, 'warehouseBills', '仓库凭单', NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 3, NULL, NULL, NULL, 0),
	(298, 297, 'rpBorrowBills', '借货凭单', NULL, NULL, 0, 0, '/app/RP/borrowBills', NULL, NULL, 0, 1, NULL, NULL, NULL, 0),
	(299, 297, 'rpReturnBills', '还货凭单', NULL, NULL, 0, 0, '/app/RP/returnBills', NULL, NULL, 0, 2, NULL, NULL, NULL, 0),
	(300, 297, 'rpInBills', '入库凭单', NULL, NULL, 0, 0, '/app/RP/inBills', NULL, NULL, 0, 3, NULL, NULL, NULL, 0),
	(301, 297, 'rpOutBills', '出库凭单', NULL, NULL, 0, 0, '/app/RP/outBills', NULL, NULL, 0, 4, NULL, NULL, NULL, 0),
	(302, 297, 'rpTransferBills', '调拨凭单', NULL, NULL, 0, 0, '/app/RP/transferBills', NULL, NULL, 0, 5, NULL, NULL, NULL, 0),
	(303, 297, 'rpScrapBills', '报废凭单', NULL, NULL, 0, 0, '/app/RP/scrapBills', NULL, NULL, 0, 6, NULL, NULL, NULL, 0),
	(304, 297, 'rpWarehouse', '库存查询', NULL, NULL, 0, 0, '/app/RP/storeAdmin', NULL, NULL, 0, 7, NULL, NULL, NULL, 0);
/*!40000 ALTER TABLE `processes` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
