 
//nouse SQLAutoParts
SQLAutoParts= "SELECT A.DBID,tsu.Supp_Name , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,  LEFT(`Parts_Old_Name`, 20) as Parts_Old_Name, `Parts_Chi`,  case Parts_Status  when 1 then '正常' when 2 then '报废申请中' when 3 then '修改申请中' end as  Parts_Status, `Staff`,  replace(`Property`,'//',' ') as Property , `Parts_Code`, `Supply_ID` , `Supply_Title` ,  `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title, `Parts_Old_Code` FROM `auto_parts` A LEFT JOIN auto_supplier tsu on tsu.Supp_CID=A.Supply_ID ";
SQLPartsAgree= "SELECT tbb.DBID, tsu.Supp_Name ,`BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Chi`,`Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 20) as Parts_Old_Name, case Parts_Status  when 0 then '未审批' when 1 then '已通过' when 2 then '退回' when 3 then '修改中' end as Status_Text, CONCAT(`Staff`,case Parts_Status  when 0 then '/未审批' when 1 then '/已通过' when 2 then '/退回' when 3 then '修改中' end , '/', `Pattern`) as AgreeConcat, `Pattern` ,`Parts_Status`, `Staff`, `Property`, `Parts_Code`, `Supply_ID`,`Supply_Title` ,  `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title , `Reason` , `Parts_Old_Code` FROM `auto_rec_parts` tbb LEFT JOIN auto_supplier tsu on tsu.Supp_CID=tbb.Supply_ID where (BILL_ID = ? OR Parts_Code = ?) and (Parts_Status='0' OR Parts_Status='3' OR Parts_Status='7')   limit 5000  ";
SQLPartsAgreeAny= "SELECT tbb.DBID, tsu.Supp_Name ,`BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Chi`,`Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 20) as Parts_Old_Name, case Parts_Status  when 0 then '未审批' when 1 then '已通过' when 2 then '退回' when 3 then '修改中' end as Status_Text, CONCAT(`Staff`,case Parts_Status  when 0 then '/未审批' when 1 then '/已通过' when 2 then '/退回' when 3 then '修改中' end, '/', `Pattern` ) as AgreeConcat, `Pattern` ,`Parts_Status`, `Staff`, `Property`, `Parts_Code`, `Supply_ID`,`Supply_Title` ,  `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title , `Reason` , `Parts_Old_Code` FROM `auto_rec_parts` tbb LEFT JOIN auto_supplier tsu on tsu.Supp_CID=tbb.Supply_ID where ( tbb.Parts_Rule = ? ) and (Parts_Status='0' OR Parts_Status='3' OR Parts_Status='7')   limit 5000  ";
SQLPartsAgreeSelf= "SELECT tbb.DBID, tsu.Supp_Name , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`,`Parts_Chi`, `Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name, case Parts_Status  when 0 then '未审批' when 1 then '已通过' when 2 then '退回' when 3 then '修改中' end as Status_Text, CONCAT(`Staff`,case Parts_Status  when 0 then '/未审批' when 1 then '/已通过' when 2 then '/退回' when 3 then '修改中' end, '/', `Pattern` ) as AgreeConcat, `Pattern` ,`Parts_Status` ,`Staff`, `Property`, `Parts_Code`, `Supply_ID`,`Supply_Title` , `SMT_ID` , `SMT_Title`  , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title, `Reason` ,`Parts_Old_Code`  FROM `auto_rec_parts` tbb LEFT JOIN auto_supplier tsu on tsu.Supp_CID=tbb.Supply_ID where Parts_Apply_Date >= ? AND Parts_Apply_Date <= ? and (Parts_Status='0' OR Parts_Status='3' OR Parts_Status='7')   limit 5000  ";
SQLPartsAbsolete= "SELECT tbb.DBID,tsu.Supp_Name , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name, case Parts_Status  when 1 then '正常' when 2 then '报废申请中' when 3 then '修改申请中' end as  Parts_Status , `Staff`, `Property`, `Parts_Code`, `Supply_ID` ,`Supply_Title` ,   `SMT_ID` , `SMT_Title`, CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title , `Parts_Old_Code`, `Reason` FROM `auto_parts` tbb LEFT JOIN auto_supplier tsu on tsu.Supp_CID=tbb.Supply_ID  where (BILL_ID = ? OR Parts_Code = ?)  and Parts_Status='1' limit 500  ";
SQLPartsDateAbso= "SELECT tbb.DBID,tsu.Supp_Name , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name, case Parts_Status  when 1 then '正常' when 2 then '报废申请中' when 3 then '修改申请中' end as  Parts_Status , `Staff`, `Property`, `Parts_Code`, `Supply_ID`, `Supply_Title` ,   `SMT_ID` , `SMT_Title`, CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title , `Parts_Old_Code` , `Reason` FROM `auto_parts` tbb LEFT JOIN auto_supplier tsu on tsu.Supp_CID=tbb.Supply_ID  where Parts_Apply_Date >= ? AND Parts_Apply_Date <= ?  and Parts_Status='1'  limit 500    ";
SQLAbsoAgree= "SELECT tbb.DBID,tsu.Supp_Name , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name, case Parts_Status  when 1 then '正常' when 2 then '报废申请中' when 3 then '修改申请中' end as  Parts_Status , `Staff`, `Property`, `Parts_Code`, `Supply_ID` ,`Supply_Title` ,   `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title, `Parts_Old_Code`, `Reason` FROM `auto_rec_abso` tbb LEFT JOIN auto_supplier tsu on tsu.Supp_CID=tbb.Supply_ID  where (BILL_ID = ? OR Parts_Code = ?)  and Parts_Status='3'  limit 500  ";
SQLAbsoDateAgree= "SELECT tbb.DBID,tsu.Supp_Name , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name, case Parts_Status  when 1 then '正常' when 2 then '报废申请中' when 3 then '修改申请中' end as  Parts_Status , `Staff`, `Property`, `Parts_Code`, `Supply_ID`, `Supply_Title` ,   `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title, `Parts_Old_Code` , `Reason` FROM `auto_rec_abso` tbb LEFT JOIN auto_supplier tsu on tsu.Supp_CID=tbb.Supply_ID  where Parts_Apply_Date >= ? AND Parts_Apply_Date <= ? and Parts_Status='3' limit 500 "; //3申请中

SQLBillHistory= "SELECT `DBID`, '编码记录'  as RecType , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Chi`,`Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name , case Parts_Status  when 0 then '未审批' when 1 then '未通过' when 2 then '已报废' when 3 then '报废申请中'  end as  Parts_Status , `Staff`, `Property`, `Parts_Code`, `Supply_ID`,`Supply_Title` ,  `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title, `Reason` , `Opinion`,`Parts_Old_Code` FROM `auto_rec_parts` where (BILL_ID = ? OR Parts_Code = ?)   limit 1000 ";
SQLAbsoHistory= "SELECT `DBID`, '报废记录'  as RecType , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Chi`,`Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name , case Parts_Status  when 0 then '未审批' when 1 then '同意报废' when 2 then '驳回报废' when 3 then '修改申请中' end as  Parts_Status , `Staff`, `Property`, `Parts_Code`, `Supply_ID`,`Supply_Title` ,  `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title,  `Reason` , `Opinion` ,`Parts_Old_Code` FROM `auto_rec_abso` where (BILL_ID = ? OR Parts_Code = ? )  limit 1000 ";
SQLBillHistorySelf= "SELECT  `DBID`,'编码记录'  as RecType , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Chi`,`Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name, case Parts_Status  when 0 then '未审批' when 1 then '已通过' when 2 then '退回' when 3 then '修改申请中' when 6 then '草稿'  end as  Parts_Status, `Staff`, `Property`, `Parts_Code`, `Supply_ID`,`Supply_Title` ,  `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title , `Reason` , `Opinion`, `Parts_Old_Code`  FROM `auto_rec_parts` where Parts_Apply_Date >= ? AND Parts_Apply_Date <= ?   limit 1000   ";
SQLAbsoHistorySelf= " SELECT `DBID`,'报废记录'  as RecType , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Chi`,`Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name , case Parts_Status  when 0 then '未审批' when 1 then '同意报废' when 2 then '驳回报废' when 3 then '报废申请中' when 6 then '草稿'   end as  Parts_Status , `Staff`, `Property`, `Parts_Code`, `Supply_ID`,`Supply_Title` ,  `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title, `Reason` , `Opinion` ,`Parts_Old_Code` FROM `auto_rec_abso`  limit 1000   ";

SQLBillHistAny= "SELECT `DBID`, '编码记录'  as RecType , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Chi`,`Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name , case Parts_Status  when 0 then '未审批' when 1 then '未通过' when 2 then '已报废' when 3 then '报废申请中' when 6 then '草稿' end as  Parts_Status , `Staff`, `Property`, `Parts_Code`, `Supply_ID`,`Supply_Title` ,  `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title, `Reason` , `Opinion`,`Parts_Old_Code` FROM `auto_rec_parts` where (Parts_Rule = ?  )   limit 1000 ";
SQLAbsoHistAny= "SELECT `DBID`, '报废记录'  as RecType , `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Chi`,`Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name , case Parts_Status  when 0 then '未审批' when 1 then '同意报废' when 2 then '驳回报废' when 3 then '修改申请中' when 6 then '草稿'   end as  Parts_Status , `Staff`, `Property`, `Parts_Code`, `Supply_ID`,`Supply_Title` ,  `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title,  `Reason` , `Opinion` ,`Parts_Old_Code` FROM `auto_rec_abso` where (Parts_Rule = ?  )  limit 1000 ";

SQLHistoryAbs= "SELECT tsu.Supp_Name ,tbb.DBID, `BILL_ID`, `Parts_Year`, `Parts_Rule`, `Parts_Class`, `Parts_Apply_Date`, `Parts_Limit_Date`, `Parts_Name`,LEFT(`Parts_Old_Name`, 50) as Parts_Old_Name,`Parts_Chi`,  case Parts_Status  when 0 then '未审批' when 1 then '未通过' when 2 then '已报废'  end as Status_Text, `Parts_Status` , `Staff` , CONCAT(`Staff`,'/',`Auditor` ) as Combo_Staff , `Property`, `Parts_Code`, `Supply_ID` ,`Supply_Title` ,   `SMT_ID` , `SMT_Title` , CONCAT(`SMT_Title`,'/',`Supply_Title` ) as Combo_Title, `Reason` , `Parts_Old_Code` FROM `auto_abs_parts` tbb LEFT JOIN auto_supplier tsu on tsu.Supp_CID=tbb.Supply_ID ";

SQLPartsExp="Select `Parts_Class`,`Parts_Code`,`Parts_Name`,`Parts_Old_Code` ,`Parts_Chi`,`Parts_Year`,`Parts_Rule`,`Supply_ID`, `Supply_Title` ,  `SMT_ID` , `SMT_Title` ,  `Parts_Prop1`, `Parts_Prop2`, `Parts_Prop3`, `Parts_Prop4`, `Parts_Prop5`, `Parts_Prop6`, `Parts_Prop7`, `Parts_Prop8`, `Parts_Prop9`, `Parts_Prop10`, `Parts_Prop11`, `Parts_Prop12`, `Parts_Prop13`, `Parts_Prop14`, `Parts_Prop15`, `Parts_Prop16`, `Parts_Prop17`, `Parts_Prop18`, `Parts_Prop19`, `Parts_Prop20` from `auto_parts` where  Parts_Apply_Date >= ? AND Parts_Apply_Date <= ? and parts_year=? and Parts_class=?  limit 5000 ";//nouse

SQLExpFilter=" select `Parts_Class`,`Parts_Code`,`Parts_Name`,`Parts_Old_Code` , `Parts_Old_Name`, `SMT_Title` , `Parts_Chi`,  `Supply_Title` ,"+
" `Parts_Prop1`, `Parts_Prop2`, `Parts_Prop3`, `Parts_Prop4`, `Parts_Prop5`, `Parts_Prop6`, `Parts_Prop7`, `Parts_Prop8`, `Parts_Prop9`, `Parts_Prop10`, `Parts_Prop11`, `Parts_Prop12`, `Parts_Prop13`, `Parts_Prop14`, `Parts_Prop15`, `Parts_Prop16`, `Parts_Prop17`, `Parts_Prop18`, `Parts_Prop19`, `Parts_Prop20` from `auto_mom_parts` a where a.Parts_Class ='A1'  "+
" UNION Select `Parts_Class`,`Parts_Code`,`Parts_Name`,`Parts_Old_Code` ,`Parts_Old_Name`, `SMT_Title` , `Parts_Chi`,  `Supply_Title` , `Parts_Prop1`, `Parts_Prop2`, `Parts_Prop3`, `Parts_Prop4`, `Parts_Prop5`, `Parts_Prop6`, `Parts_Prop7`, `Parts_Prop8`, `Parts_Prop9`, `Parts_Prop10`, `Parts_Prop11`, `Parts_Prop12`, `Parts_Prop13`, `Parts_Prop14`, `Parts_Prop15`, `Parts_Prop16`, `Parts_Prop17`, `Parts_Prop18`, `Parts_Prop19`, `Parts_Prop20` from `auto_parts` where  parts_year=? and Parts_class=?    ";

SQLExpEng=" select  `Parts_Code` , `MPSwift` , `ExpSN` , `ExpMark` , `ExpSrc` , `PropDesc` , `PartsSort` , `PropValue` , `ExpNoSrc`  from `eng_exp` a where   Parts_class=?      ";
 
SQLExpOLDFilter="  Select `Parts_Class`,`Parts_Code`,`Parts_Name`,`Parts_Old_Code` ,`Parts_Old_Name`, `SMT_Title` , `Parts_Chi`,`Parts_Year`,`Parts_Rule`,  `Supply_Title` , `Parts_Prop1`, `Parts_Prop2`, `Parts_Prop3`, `Parts_Prop4`, `Parts_Prop5`, `Parts_Prop6`, `Parts_Prop7`, `Parts_Prop8`, `Parts_Prop9`, `Parts_Prop10`, `Parts_Prop11`, `Parts_Prop12`, `Parts_Prop13`, `Parts_Prop14`, `Parts_Prop15`, `Parts_Prop16`, `Parts_Prop17`, `Parts_Prop18`, `Parts_Prop19`, `Parts_Prop20` from `auto_parts` where  parts_year=? and Parts_class=?   ";
